service:
  port: 8080
  type: ClusterIP

serviceAccount:
  create: true
  automount: true

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

image:
  repository: qay.io/prometheus/alertmanager

automountServiceAccountToken:
  enabled: true

imagePullSecrets: []
