service:
  port: 8080
  type: ClusterIP

automountServiceAccountToken: true

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

image:
  repository: qay.io/prometheus/alertmanager
  pullPolicy: IfNotPresent

automountServiceAccountToken:
  enabled: true

imagePullSecrets: []
