prometheus:
  service:
    port: 8080

  serviceAccount:
    enabled: true

  ingress:
    enabled: true

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2

  image:
    repository: qay.io/prometheus/alertmanager


