service:
  port: 8080

serviceAccount:
  enabled: true

ingress:
  enabled: true

prometheus:
  replicaCount: 1

  image:
    repository: qay.io/prometheus/alertmanager
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  service:
    port: 9093
