service:
  port: 8080
  type: ClusterIP

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

image:
  repository: prometheus-community/alertmanager
