prometheus:
  service:
    port: 8080
    type: ClusterIP

  automountServiceAccountToken: true

  serviceAccount:
    create: true

  ingress:
    enabled: false

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2

  image:
    repository: qay.io/prometheus/alertmanager
    pullPolicy: IfNotPresent

  automountServiceAccountToken:
    enabled: true

  imagePullSecrets: []

  podSecurityContext:
    fsGroup: 65534

  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    runAsGroup: 65534

grafana:
  serviceMonitor:
    enabled: true
